---
- hosts: dev
  remote_user: dougala
  vars:
    - home_dir: /Users/dougala/
    - brew_packages:
       - boot2docker
       - brew-cask
       - ccm
       - htop
       - gradle
       - maven
       - node
       - phantomjs198
       - python
       - scala
       - SBT
       - tig
       - wget
    - cask_packages:
       - adobe-reader
       - bettertouchtool
       - caffeine
       - dropbox
       - google-drive
       - google-chrome
       - intellij-idea-ce
       - iterm2
       - java6
       - java7
       - java
       - origin
       - shiftit
       - skype
       - slack
       - sonos
       - spotify
       - spotify-notifications
       - sublime-text
       - teamviewer
       - vagrant
       - virtualbox
       - yed
  roles:
    - general
    - ruby
    - ccm
