---
- hosts: dev
  remote_user: dougala
  vars:
    - home_dir: /Users/dougala/
    - brew_packages:
       - brew-cask
       - htop
       - gradle
       - maven
       - python
       - scala
       - SBT
       - tig
       - wget
    - cask_packages:
       - caffeine
       - dropbox
       - google-drive
       - google-chrome
       - intellij-idea-ce
       - iterm2
       - java6
       - java7
       - java
       - macports
       - skype
       - sonos
       - spotify
       - spotify-notifications
       - sublime-text
       - vagrant
       - virtualbox
  roles:
    - general
#    - ruby
#    - ccm