---
- name: Install brew packages
  homebrew: update_homebrew=yes name={{ item }}
  with_items: brew_packages

- name: Tap caskroom/versions
  homebrew_tap: tap=caskroom/versions

- homebrew_cask: name={{ item }} state=installed
  with_items: cask_packages

- name: Install functions etc to home directory
  copy: src={{ item }} dest={{ home_dir }}
  with_items:
    - functions.sh
    - .git-completion.bash
    - .gitconfig

- name: Source functions in bash home
  lineinfile: dest=~/.bash_profile line="source ~/functions.sh" create=yes

- name: Source git completions
  lineinfile: dest=~/.bash_profile line="source ~/.git-completion.bash" create=yes

- name: Create workspace directory
  file: path={{ home_dir }}Workspace state=directory

- name: Show hidden files
  command: defaults write com.apple.finder AppleShowAllFiles YES